// <auto-generated />
using System;
using Bifrost.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bifrost.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528205619_CreateDiscipline")]
    partial class CreateDiscipline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.AcademicCenterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_season_id");

                    b.Property<decimal?>("AvgScore")
                        .HasColumnType("decimal(8,6)")
                        .HasColumnName("avg_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentSeasonId")
                        .IsUnique();

                    b.ToTable("academic_centers");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.AcademicCenterMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademicCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_center_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AcademicCenterId");

                    b.HasIndex("UserId", "AcademicCenterId")
                        .IsUnique();

                    b.ToTable("academic_center_members");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.AssessmentSeasonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_time");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("varchar(7)")
                        .HasColumnName("period");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_time");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Period")
                        .IsUnique();

                    b.ToTable("assessment_seasons");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.CoordinationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_season_id");

                    b.Property<decimal?>("AvgScore")
                        .HasColumnType("decimal(8,6)")
                        .HasColumnName("avg_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentSeasonId")
                        .IsUnique();

                    b.ToTable("coordinations");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.CoordinationMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoordinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("coordination_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CoordinationId");

                    b.HasIndex("UserId", "CoordinationId")
                        .IsUnique();

                    b.ToTable("coordination_members");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("courses");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.DisciplineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_season_id");

                    b.Property<decimal?>("AvgScore")
                        .HasColumnType("decimal(8,6)")
                        .HasColumnName("avg_score");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("professor_id");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentSeasonId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("disciplines");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.DisciplineStudentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("discipline_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DisciplineId", "UserId")
                        .IsUnique();

                    b.ToTable("discipline_students");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleOpenid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("google_openid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("profile");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleOpenid")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.AcademicCenterEntity", b =>
                {
                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.AssessmentSeasonEntity", "AssessmentSeason")
                        .WithMany()
                        .HasForeignKey("AssessmentSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentSeason");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.AcademicCenterMemberEntity", b =>
                {
                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.AcademicCenterEntity", "AcademicCenter")
                        .WithMany("AcademicCenterMembers")
                        .HasForeignKey("AcademicCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicCenter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.AssessmentSeasonEntity", b =>
                {
                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.CoordinationEntity", b =>
                {
                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.AssessmentSeasonEntity", "AssessmentSeason")
                        .WithMany()
                        .HasForeignKey("AssessmentSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentSeason");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.CoordinationMemberEntity", b =>
                {
                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.CoordinationEntity", "Coordination")
                        .WithMany("CoordinationMembers")
                        .HasForeignKey("CoordinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.DisciplineEntity", b =>
                {
                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.AssessmentSeasonEntity", "AssessmentSeason")
                        .WithMany()
                        .HasForeignKey("AssessmentSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.UserEntity", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentSeason");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.DisciplineStudentEntity", b =>
                {
                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.DisciplineEntity", "Discipline")
                        .WithMany("DisciplineStudents")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.UserEntity", b =>
                {
                    b.HasOne("Bifrost.Infrastructure.Persistence.Entity.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.AcademicCenterEntity", b =>
                {
                    b.Navigation("AcademicCenterMembers");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.CoordinationEntity", b =>
                {
                    b.Navigation("CoordinationMembers");
                });

            modelBuilder.Entity("Bifrost.Infrastructure.Persistence.Entity.DisciplineEntity", b =>
                {
                    b.Navigation("DisciplineStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
